FROM python:3.8

WORKDIR /build
COPY . .

ENV TZ="Asia/Shanghai"
ENV EK_IN_DOCKER="1"

RUN python -m venv /opt/venv \
    && . /opt/venv/bin/activate \
    && pip install --no-cache-dir -U pip setuptools wheel \
    && pip install --no-cache-dir -e . \
    && ln -s /build/scripts/docker-entrypoint-dev.sh /entrypoint.sh \
    && chmod +x /entrypoint.sh

WORKDIR /app

RUN touch config.toml
ENV PATH="/opt/venv/bin:$PATH"

ENTRYPOINT ["/entrypoint.sh"]
